### ISSUE TITLE
Config with useSpring

### ISSUE THREAD

**Issue by gmenih341** [drcmda/react-spring#306]
I'm not sure if I'm missing something, but is there a way to set the `config` with `useSpring`?

I'm trying to set the ease and the duration of a transition with `useSpring`, but  I can't find a way how to achieve this.

**Comment by drcmda** [comment]
sure, just dump all the props into it,

    useSpring({ ..., config: { ... } })

It basically follows Keyframes lead there: http://react-spring.surge.sh/keyframes

**Comment by gmenih341** [comment]
@drcmda I know this is quite experimental, but there seems to be a bug with `useSpring`. When setting the value of any prop to `0`, in combination with the `duration` config, it will not properly set the very last value of the prop (after the animation ends, it should set it to `0`, but it's stuck on whatever value it was before it).

See here: https://codesandbox.io/s/ryp2kj73np

Click on the button, and see that whenever the value should be set to 0 it's stuck on some arbitrary value.

**Comment by drcmda** [comment]
Interesting. Indeed the width seems to be ok, but innerText is one frame behind in both duration and spring settings. The box will make it easy to track, thanks! I'll notify you when it's fixed.

**Comment by drcmda** [comment]
Should be fixed.

**Comment by gmenih341** [comment]
It fixes the issue with `innerText`, but I can still reproduce this when using `scrollTop` property.. It's not that big of a deal. as just interpolating it to string fixes the issue, but just thought you might want to know about it.

Here's an updated example of the issue: https://codesandbox.io/s/oj0jx0m809

**Comment by drcmda** [comment]
Oh my, it's the same issue, sorry. Made another patch release (6.1.8).

**Comment by gmenih341** [comment]
Yep, working now 👌 Thanks for your time :) 

Closing this now
