### ISSUE TITLE
Transition leave has undefined as first argument

### ISSUE THREAD

**Issue by andtos90** [drcmda/react-spring#75]
I just started a new project with create-react-app and included the tree example without changes. When a node is clicked everything works as expected but every time you try to collapse a node this error pops up:

> Uncaught TypeError: Cannot read property 'source' of undefined

This error occurs because the `leave` prop of the `Transition` component has `undefined` as first argument. This happens only with react-spring version >= 5.0.1 (5.0.0 is fine). 

### Repro:
https://github.com/andtos90/react-spring-onleave-bug with react-spring 5.1.0

**Comment by drcmda** [comment]
should hopefully be fixed in 5.1.1

**Comment by Noor0** [comment]
i'm on v8.0.27 but i'm still getting the error, this is what my code looks like
```
const transitions = useTransition(
	show ? dataWithPosition : [],
	(item, i) => (extractKey instanceof Function ? extractKey(item) : i),
	{
	          from: ({ position }) => ({
		  transform: `translateY(-${position * 100}%)`,
		  opacity: 0,
		}),
		enter: { transform: `translateY(0%)`, opacity: 1 },
		leave: ({ position }) => ({
			transform: `translateY(-${position * 100}%)`,
			opacity: 0,
		}),
		config: { duration: 200 },
	},
);
```

**Comment by aleclarson** [comment]
@Noor0 Try with v9 beta: `npm install react-spring@next`

If that doesn't fix it, please open a new issue.
